allinbits/cosmos-cash

x/identifier/client/cli/cli_test.go, x/identifier/client/cli/tx.go
Add integration test suite to the identifier module
- `make test`
=> feat: add integration test suite

Makefile, proto/identifier/tx.proto, x/ibc-identifier/types/genesis.pb.go, x/ibc-identifier/types/transfer.pb.go, x/ibc-identifier/types/tx.pb.go, x/identifier/client/cli/cli_test.go, x/identifier/client/cli/query.go, x/identifier/client/cli/tx.go, x/identifier/handler.go, x/identifier/handler_test.go, x/identifier/keeper/identifier.go, x/identifier/keeper/keeper.go, x/identifier/keeper/keeper_test.go, x/identifier/keeper/msg_server.go, x/identifier/keeper/msg_server_test.go, x/identifier/module.go, x/identifier/types/codec.go, x/identifier/types/errors.go, x/identifier/types/genesis.pb.go, x/identifier/types/identifier.go, x/identifier/types/identifier.pb.go, x/identifier/types/msg.go, x/identifier/types/query.pb.go, x/identifier/types/tx.pb.go, x/issuer/types/genesis.pb.go, x/issuer/types/issuer.pb.go
Adding authentication to the DID document
- `make init-dev`
In another terminal
- `go run main.go tx identifier create-identifier --from validator --chain-id cash -y`
- `go run main.go tx identifier add-authentication `id of did` `pubKey` --from validator --chain-id cash -y`
=> feat(auth): add authentication to did document

network/local-relayer/chains/cash.json, network/local-relayer/chains/cash2.json, network/local-relayer/paths/cash-identifier-cash2.json, network/local-relayer/paths/cash-transfer-cash2.json, network/local-relayer/paths/cash2-transfer-cash.json, network/local-relayer/rly.sh, network/local-relayer/start-chains.sh, scripts/seeds/98_ibc_transfer_seeds.sh, scripts/seeds/99_ibc_identifier.sh, x/ibc-identifier/keeper/msg_server.go
Setting up relayer for local development
closes: #33 
- `./network/local-relayer/start-chains`
In another terminal
- `cd ./network/local-relayer`
- `./rly.sh`
In another terminal
- `./scripts/seeds/99_ibc_identifier.sh`
=> feat(rly): adding basic relayer set up

scripts/seeds/05_money_mule.sh, x/identifier/keeper/identifier.go, x/identifier/keeper/keeper.go
Adding money mule scenario to seeds
closes: #44 
In another terminal
- `make seed`
- `./scripts/seeds/05_money_mule.sh`
=> feat(aml): adding money mule scenario

config.yml
Works out of the box with `starport serve`.
Run `starport serve -r --rebuild-proto-once` to generate JS clients for custom modules as well as for standard Cosmos SDK modules.
=> chore: added starport config.yml

scripts/seeds/06_selective_disclosure.sh, x/verifiable-credential-service/client/cli/tx.go
Adding the selective disclosure seed for bobs story with e-money issuer to prove identity
- `./scripts/seeds/06_selective_disclosure.sh`
=> feat(seeds): add selective disclosure seed

scripts/seeds/06_selective_disclosure.sh
Minor updates to the selective disclosure seeds
- `./scripts/seeds/06_selective_disclosure.sh`
=> chore: minor update seed for selective disclosure

proto/issuer/tx.proto, scripts/seeds/03_issuer_seeds.sh, x/issuer/client/cli/tx.go, x/issuer/keeper/handler.go, x/issuer/keeper/msg_server.go, x/issuer/keeper/msg_server_test.go, x/issuer/types/codec.go, x/issuer/types/msg.go, x/issuer/types/tx.pb.go
=> feat: add mint to the issuer module

CHANGELOG.md
Prepare changelog fro release v0.2.0
=> Prepare for v0.2.0 release

CHANGELOG.md, Makefile
=> Release v0.2.0

x/identifier/client/cli/cli_test.go, x/identifier/client/cli/tx.go, x/identifier/keeper/handler_test.go, x/identifier/keeper/msg_server.go, x/identifier/keeper/msg_server_test.go, x/issuer/types/event.go, x/verifiable-credential-service/keeper/msg_server.go, x/verifiable-credential-service/types/verifiable-credential.go
Add a check for the type of credential being created
closes: #99 
- `make test`
=> fix(creds): use enums for credential types

x/issuer/ante/ante.go, x/issuer/keeper/msg_server.go, x/issuer/types/errors.go
Updated errors
closes: #98 
Review code
=> feat(errors): update issuer errors

.chglog/CHANGELOG.tpl.md, .chglog/config.yml, Makefile
Add a set of commands and configuration to support the release process described in #130
=> chore(release): add make targets and config to simplify releases

docs/architecture/README.md, docs/architecture/adr-002-docs-structure.md
This is the first version of ADR002 for Documentation Structure for comment. Issue #129
=> feat(ADR): draft version of doc structure ADR (#129)

docs/architecture/adr-002-docs-structure.md
This ADR proposes a documentation strategy for 4 specific use cases for documentation and the proposed structure using GitHub as the Content Management System.
=> feat(ADR): Documentation Strategy (#129)

scripts/seeds/01_identifier_seeds.sh, x/did/client/cli/tx.go, x/did/keeper/msg_server.go, x/did/types/did.go, x/did/types/keys.go
Adding commands for adding verification relationships and controllers of a did document
closes: #134 
- `make seed`
=> feat(did): adding commands for relationships and controllers

docs/Explanation/README.md, docs/Explanation/articles/README.md, docs/Explanation/presentations.md, docs/README.md, docs/Reference/README.md
RFC on README structure. I have completed the READEMEs for Explanation and Reference section plus top-level.
=> feat(docs): READMEs for docs, Explanation and Reference Documentation (#148)

README.md, docs/Reference/MODULES.md
add links to various sections of the documentation
=> docs: improve main readme

go.mod, go.sum
the update introduces consensus breaking changes, refer to the changelog in the cosmos-sdk for details
=> chore: upgrade cosmos-sdk to version v0.44

scripts/seeds/04_user_seeds.sh, x/did/keeper/did.go, x/did/types/did.go, x/issuer/ante/ante.go, x/verifiable-credential/keeper/verifiable-credential.go
Updating KYC check to check user kyc credentials
closes: #244 
- `make seed`
- `./scripts/seeds/04_user_seeds.sh`
=> feat(issuer): update kyc check ante handler

x/issuer/keeper/issuer.go, x/issuer/types/msg.go
Updated msg validation
related #251 
- `make seed`
=> feat(issuer): update msg validation to check issuer did id

Makefile, scripts/seeds/01_identifier_seeds.sh, scripts/seeds/02_verifiable_credentials_seeds.sh, scripts/seeds/03_issuer_seeds.sh, x/issuer/ante/ante.go, x/issuer/ante/ante_test.go, x/verifiable-credential/keeper/verifiable-credential.go
=> fix(ante): update ante handler tests

CHANGELOG.md
=> chore: update changelog for v2.0.0

.github/workflows/docs.yaml, .gitignore, docs/Explanation/ADR/README.md, docs/Explanation/ADR/adr-005-registration-credential.md, docs/Explanation/ADR/adr-006-license-credential.md, docs/Explanation/README.md, docs/Explanation/articles/makefile, docs/Explanation/articles/regulation-paper/rpts/CosmosCashRegs.md, docs/README.md, docs/Reference/MODULES.md, docs/Reference/README.md, mkdocs.yml
=> docs: publish docs website

x/did/client/cli/aries.go
fix connection handshake between agents using anchored did
=> fix: extract X25519ECDHKW pubkey from aries response

docs/Reference/GLOSSARY.md
As I work on a new Starport glossary, I came over here to admire the Cosmos Cash glossary.
Let's make these changes to begin the path to glossary excellence:
- do not repeat the glossary term in the description
- apply technical content style standards
remain awesome!
=> quick fix for style and standard, do not repeat term

.codecov.yml, .github/workflows/ci.yaml, Makefile, x/did/keeper/did.go, x/did/keeper/msg_server.go, x/did/keeper/msg_server_test.go, x/did/spec/testing.md, x/did/types/codec.go, x/did/types/did.go, x/did/types/did_test.go, x/did/types/did_verification_material.go, x/did/types/event_test.go, x/did/types/msg.go, x/did/types/msg_test.go, x/did/types/msg_validation.go, x/did/types/msg_validation_test.go
test: add msg server test for delete controller
=> test: increase test coverage
